// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nGRgahHVGV3003KtKWU1413XRZM6g4E',
    appId: '1:761854413031:web:0b5bbe83e5287db2603a42',
    messagingSenderId: '761854413031',
    projectId: 'fitfarm-37b2f',
    authDomain: 'fitfarm-37b2f.firebaseapp.com',
    storageBucket: 'fitfarm-37b2f.firebasestorage.app',
    measurementId: 'G-7KQTKRNK9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfqsYHM0J1hisNw8On96WC9H06tZs4Dc',
    appId: '1:761854413031:android:497964eb723c952d603a42',
    messagingSenderId: '761854413031',
    projectId: 'fitfarm-37b2f',
    storageBucket: 'fitfarm-37b2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd23GBrGDX1d7q9cgLxbxCKHQafMqwgfI',
    appId: '1:761854413031:ios:b3c9ae93a375e2dc603a42',
    messagingSenderId: '761854413031',
    projectId: 'fitfarm-37b2f',
    storageBucket: 'fitfarm-37b2f.firebasestorage.app',
    iosBundleId: 'com.fitfarm.fitFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd23GBrGDX1d7q9cgLxbxCKHQafMqwgfI',
    appId: '1:761854413031:ios:b3c9ae93a375e2dc603a42',
    messagingSenderId: '761854413031',
    projectId: 'fitfarm-37b2f',
    storageBucket: 'fitfarm-37b2f.firebasestorage.app',
    iosBundleId: 'com.fitfarm.fitFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nGRgahHVGV3003KtKWU1413XRZM6g4E',
    appId: '1:761854413031:web:79141a45bc476784603a42',
    messagingSenderId: '761854413031',
    projectId: 'fitfarm-37b2f',
    authDomain: 'fitfarm-37b2f.firebaseapp.com',
    storageBucket: 'fitfarm-37b2f.firebasestorage.app',
    measurementId: 'G-M2YFDB9FVF',
  );
}
